version: "3"
services:
  web:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/myflaskapp
      - SECRET_KEY=xxxxxxxxxxxxxxxxxxxxxxxx
      - REDIS_URL=redis://redis:6379
    command:
      [
        "./wait-for-it.sh",
        "db:5432",
        "--",
        "flask",
        "run",
        "--host=0.0.0.0",
        "--port=5001",
      ]

    volumes:
      - .:/app
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myflaskapp
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  celery:
    build: .
    command: celery -A tasks worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
  redis:
    image: redis
volumes:
  db-data:
